blueprint:
  name: Gradual Wake-Up Light (Hue or any dimmable light)
  description: >
    Gradually turns on a light over a configurable fade duration and color temperature.
    Can be configured to run on weekdays, weekends, or both using a weekday sensor.
  domain: automation

input:
  light_entity:
    name: Target Light
    selector:
      entity:
        domain: light

  start_time:
    name: Wake-Up Start Time
    selector:
      time: {}

  fade_duration:
    name: Fade Duration (minutes)
    default: 20
    selector:
      number:
        min: 1
        max: 60
        step: 1
        unit_of_measurement: minutes
          
  light_off_duration:
    name: Light Off Duration (minutes)
    description: How long to wait before turning off the light.
    default: 30
    selector:
      number:
        min: 1
        max: 60
        unit_of_measurement: minutes
        step: 1
        mode: slider
          
  color_temp:
    name: Color Temperature (mired)
    description: Light color temperature during fade.
    default: 370
    selector:
      number:
        min: 153
        max: 500
        step: 10
        unit_of_measurement: mired
        mode: slider

  weekday_sensor:
    name: Weekday Sensor
    description: >
      A binary_sensor that is 'on' during weekdays (for example: binary_sensor.workday_sensor).
    default: binary_sensor.workday_sensor
    selector:
      entity:
        domain: binary_sensor

  active_days:
    name: Active Days
    description: Choose when this automation should run.
    default: both
    selector:
      select:
        options:
          - label: Weekdays only
            value: weekdays
          - label: Weekends only
            value: weekends
          - label: Both
            value: both

mode: restart

trigger:
  - platform: time_pattern
    minutes: "/1"  # triggers every minute

condition:
  - condition: template
    value_template: >
      {% set current = now().strftime('%H:%M') %}
      {% set target = (inputs.start_time | default('07:00'))[:5] %}
      {{ current == target }}
      
action:
  - variables:
      light: !input light_entity
      duration: !input fade_duration
      color_temp: !input color_temp
      steps: 30
      step_delay: "{{ (duration * 60 / steps) | int }}"
      off_duration: !input light_off_duration

  - service: light.turn_on
    target:
      entity_id: "{{ light }}"
    data:
      brightness: 1
      color_temp: "{{ color_temp }}"

  - repeat:
      count: "{{ steps }}"
      sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ light }}"
          data:
            brightness: "{{ (repeat.index / steps * 255) | int }}"
            color_temp: "{{ color_temp }}"
            transition: "{{ step_delay }}"
        - delay:
            seconds: "{{ step_delay }}"

  - delay:
      minutes: "{{ off_duration }}"

  - service: light.turn_off
    target:
      entity_id: "{{ light }}"

