blueprint:
  name: Gradual Wake-Up Light (Hue or any dimmable light)
  description: >
    Gradually turns on a light over a configurable fade duration and color temperature.
    Can be configured to run on weekdays or weekends using a weekday sensor.
  domain: automation

  input:
    light_entity:
      name: Target Light
      description: The light entity to fade on.
      selector:
        entity:
          domain: light

    start_time:
      name: Wake-Up Time Helper
      description: Select an input_datetime entity that holds the wake-up time.
      selector:
        entity:
          domain: input_datetime

    fade_duration:
      name: Fade Duration (minutes)
      description: How long the fade should last.
      default: 20
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
          step: 1
          mode: slider
          
    light_off_duration:
      name: Light Off Duration (minutes)
      description: How long to wait before turning off the light.
      default: 30
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
          step: 1
          mode: slider
          
    color_temp:
      name: Color Temperature (mired)
      description: Light color temperature during fade.
      default: 370
      selector:
        number:
          min: 153
          max: 500
          step: 10
          unit_of_measurement: mired
          mode: slider

    weekday_sensor:
      name: Weekday Sensor
      description: >
        A binary_sensor that is 'on' during weekdays (for example: binary_sensor.workday_sensor).
      default: binary_sensor.workday_sensor
      selector:
        entity:
          domain: binary_sensor

    active_days:
      name: Active Days
      description: Choose when this automation should run.
      default: weekdays
      selector:
        select:
          options:
            - label: Weekdays only
              value: weekdays
            - label: Weekends only
              value: weekends

mode: restart

variables:
  active_days: !input 'active_days'
  weekday_sensor_entity: !input 'weekday_sensor'
  is_weekday: "{{ states(weekday_sensor_entity).state == 'on' }}"
  light: !input 'light_entity'
  fade_duration_minutes: !input 'fade_duration'
  color_temp_value: !input 'color_temp'
  light_off_minutes: !input 'light_off_duration'
  steps: 30
  step_delay: "{{ (fade_duration_minutes * 60 / steps) | int }}"

trigger:
  - platform: time
    at: !input 'start_time'

condition:
  - condition: template
    value_template: >
      {{ 
        (active_days == 'weekdays' and is_weekday) or
        (active_days == 'weekends' and not is_weekday)
      }}

action:
  - service: light.turn_on
    target:
      entity_id: "{{ light }}"
    data:
      brightness: 1
      color_temp: "{{ color_temp_value }}"

  - repeat:
      count: "{{ steps }}"
      sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ light }}"
          data:
            brightness: "{{ (repeat.index / steps * 255) | int }}"
            color_temp: "{{ color_temp_value }}"
            transition: "{{ step_delay }}"
        - delay:
            seconds: "{{ step_delay }}"

  - delay:
      minutes: "{{ light_off_minutes }}"

  - service: light.turn_off
    target:
      entity_id: "{{ light }}"

