blueprint:
  name: Gradual Wake-Up Light (Hue or any dimmable light)
  description: >
    Gradually turns on a light over a configurable fade duration and color temperature.
    Supports different behavior for weekends.
  domain: automation
  input:
    light_entity:
      name: Target Light
      description: The light entity to fade on.
      selector:
        entity:
          domain: light

    start_time:
      name: Wake-up Start Time
      description: When to start the fade sequence.
      selector:
        time: {}

    fade_duration:
      name: Fade Duration (minutes)
      description: How long the fade should last.
      default: 20
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
          step: 1
          mode: slider

    color_temp:
      name: Color Temperature (mired)
      description: Light color temperature during fade.
      default: 370
      selector:
        number:
          min: 153
          max: 500
          step: 10
          unit_of_measurement: mired
          mode: slider

    weekend_sensor:
      name: Weekend Sensor
      description: A binary_sensor that is 'on' during weekends.
      default: binary_sensor.weekend
      selector:
        entity:
          domain: binary_sensor

    weekend_start_time:
      name: Weekend Start Time (optional)
      description: Optional different start time for weekends.
      default: ""
      selector:
        time: {}

mode: restart

trigger:
  - platform: time
    at: !input start_time
  - platform: time
    at: !input weekend_start_time

condition: []

action:
  - variables:
      light: !input light_entity
      duration: !input fade_duration
      color_temp: !input color_temp
      weekend_sensor: !input weekend_sensor
      weekend_start: !input weekend_start_time
      is_weekend: "{{ is_state(weekend_sensor, 'on') }}"
      steps: 20
      step_delay: "{{ (duration * 60 / steps) | int }}"
      trigger_time: "{{ trigger.now.time().isoformat() }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_weekend and weekend_start != '' and trigger_time == weekend_start }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              brightness: 1
              color_temp: "{{ color_temp }}"
          - repeat:
              count: "{{ steps }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ light }}"
                  data:
                    brightness: "{{ (repeat.index / steps * 255) | int }}"
                    color_temp: "{{ color_temp }}"
                    transition: "{{ step_delay }}"
                - delay:
                    seconds: "{{ step_delay }}"
    default:
      - service: light.turn_on
        target:
          entity_id: "{{ light }}"
        data:
          brightness: 1
          color_temp: "{{ color_temp }}"
      - repeat:
          count: "{{ steps }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: "{{ light }}"
              data:
                brightness: "{{ (repeat.index / steps * 255) | int }}"
                color_temp: "{{ color_temp }}"
                transition: "{{ step_delay }}"
            - delay:
                seconds: "{{ step_delay }}"

