mode: restart

trigger:
  - platform: time
    at: !input start_time
  - platform: time
    at: !input weekend_start_time

condition: []

action:
  - variables:
      light: !input light_entity
      duration: !input fade_duration
      color_temp: !input color_temp
      weekend_sensor: !input weekend_sensor
      weekend_start: !input weekend_start_time
      is_weekend: "{{ is_state(weekend_sensor, 'on') }}"
      steps: 20
      step_delay: "{{ (duration * 60 / steps) | int }}"
      trigger_time: "{{ trigger.now.time().isoformat() }}"

  - choose:
      # Weekend branch
      - conditions:
          - condition: template
            value_template: "{{ is_weekend and weekend_start != '' and trigger_time == weekend_start }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              brightness: 1
              color_temp: "{{ color_temp }}"
          - repeat:
              count: "{{ steps }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ light }}"
                  data:
                    brightness: "{{ (repeat.index / steps * 255) | int }}"
                    color_temp: "{{ color_temp }}"
                    transition: "{{ step_delay }}"
                - delay:
                    seconds: "{{ step_delay }}"
    default:
      - service: light.turn_on
        target:
          entity_id: "{{ light }}"
        data:
          brightness: 1
          color_temp: "{{ color_temp }}"
      - repeat:
          count: "{{ steps }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: "{{ light }}"
              data:
                brightness: "{{ (repeat.index / steps * 255) | int }}"
                color_temp: "{{ color_temp }}"
                transition: "{{ step_delay }}"
            - delay:
                seconds: "{{ step_delay }}"

